name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ruff pytest

      - name: Lint and Format
        run: |
          ruff check .
          ruff format --check .

      - name: Run Tests
        run: PYTHONPATH=$(pwd) pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sesh97
          password: dckr_pat_i8-rOhp9p0zs5w4HW5C08qShcks

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sesh97/fastapi-website-ci:latest
